# Generated by Django 5.1 on 2024-08-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("startask", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
