# Generated by Django 5.1 on 2024-08-17 15:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("startask", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="completed",
            new_name="status_completed",
        ),
    ]
