# Generated by Django 5.1 on 2024-08-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("startask", "0002_rename_completed_task_status_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status_completed",
            field=models.CharField(
                choices=[
                    ("todo", "To Do"),
                    ("in_progress", "In Progress"),
                    ("finished", "Finished"),
                ],
                default="todo",
                max_length=15,
            ),
        ),
    ]
