# Generated by Django 5.1 on 2024-08-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("startask", "0002_alter_task_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.CharField(
                blank=True, default="Sem descrição...", max_length=200, null=True
            ),
        ),
    ]
